# Generated by Django 3.2.21 on 2023-09-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(1, '4:00 pm - 6:00 pm'), (2, '4:15 pm - 6:15 pm'), (3, '4:30 pm - 6:30 pm'), (4, '4:45 pm - 6:45 pm'), (5, '5:00 pm - 7:00 pm'), (6, '5:15 pm - 7:15 pm'), (7, '5:30 pm - 7:30 pm'), (8, '5:45 pm - 7:45 pm'), (9, '6:00 pm - 8:00 pm'), (10, '6:15 pm - 8:15 pm'), (11, '6:30 pm - 8:30 pm'), (12, '6:45 pm - 8:45 pm'), (13, '7:00 pm - 9:00 pm'), (14, '7:15 pm - 9:15 pm'), (15, '7:30 pm - 9:30 pm'), (16, '7:45 pm - 9:45 pm'), (17, '8:00 pm - 10:00 pm')], default=1)),
                ('number_of_guests', models.PositiveIntegerField(default=2)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
