# Generated by Django 3.2.21 on 2023-09-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_user',
            new_name='user',
        ),
    ]
