# Generated by Django 3.2.21 on 2023-09-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_customer_user_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default='8:00 pm - 10:00 pm'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[('4:00 pm - 6:00 pm', '4:00 pm - 6:00 pm'), ('4:15 pm - 6:15 pm', '4:15 pm - 6:15 pm'), ('4:30 pm - 6:30 pm', '4:30 pm - 6:30 pm'), ('4:45 pm - 6:45 pm', '4:45 pm - 6:45 pm'), ('5:00 pm - 7:00 pm', '5:00 pm - 7:00 pm'), ('5:15 pm - 7:15 pm', '5:15 pm - 7:15 pm'), ('5:30 pm - 7:30 pm', '5:30 pm - 7:30 pm'), ('5:45 pm - 7:45 pm', '5:45 pm - 7:45 pm'), ('6:00 pm - 8:00 pm', '6:00 pm - 8:00 pm'), ('6:15 pm - 8:15 pm', '6:15 pm - 8:15 pm'), ('6:30 pm - 8:30 pm', '6:30 pm - 8:30 pm'), ('6:45 pm - 8:45 pm', '6:45 pm - 8:45 pm'), ('7:00 pm - 9:00 pm', '7:00 pm - 9:00 pm'), ('7:15 pm - 9:15 pm', '7:15 pm - 9:15 pm'), ('7:30 pm - 9:30 pm', '7:30 pm - 9:30 pm'), ('7:45 pm - 9:45 pm', '7:45 pm - 9:45 pm'), ('8:00 pm - 10:00 pm', '8:00 pm - 10:00 pm')], default='4:00 pm - 6:00 pm'),
        ),
    ]
